### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by PhilHansonGH** [wuusn/miyano#17]
- For some reason, I can’t have more than one hyperlink per carriage return.
- The post preview on the main page doesn’t parse the Bear Notes url’s, so you see the Markdown code.

URL: https://apatheticpoetic.com/Bear_App_and_Miyano/

**Comment by wuusn** [comment]
1. Could you show me an example of what you mean that can't have more than one hyperlink per carriage return. I didn't get the point of the word `carriage`.
2. There's an issue of the **preview** itself. You know, preview only has one part of the post. let's say, if we have a **table**, but the preview only contains the half **table**, how could we show it? Keep the origin markdown in the preview prevent dealing with the uncompleted elements.

**Comment by peterwooley** [comment]
I believe Phil was was referring to an issue where only a single link per paragraph works. I think the regex for `REGEXP_LINKURL` in `beardown/lib/beardown/spans/linkurl.rb` is acting greedy, but I'm sure how to fix it.

Here's an example where I have multiple links in a single paragraph that look like this in Bear:

![multiple-links-in-bear](https://user-images.githubusercontent.com/42030/50679097-c714bb80-0fb6-11e9-802f-1b478644f891.png)

But the first link extends all the way to the end of the last link in Miyano:

![multiple-links-in-miyano](https://user-images.githubusercontent.com/42030/50679159-1824af80-0fb7-11e9-8e38-6105aa115ba6.png)

If you'd like to use my text for testing, here's the markdown:

```I started listening and identifying with the stories shared in [This American Life](http://www.thisamericanlife.org/), [The Moth](http://themoth.org/), [Radiolab](http://www.radiolab.org/), and other great story-driven podcasts, which led me to discover [the difference between empathy and sympathy](https://www.youtube.com/watch?v=1Evwgu369Jw) and to begin questioning every moral position I’d ever taken.```

Thanks for creating this great tool! I've been writing in Bear for a while now but haven't done the work to get my words online again. Miyano is helping me to do just that.

**Comment by wuusn** [comment]
hi @PhilHansonGH @peterwooley ,

I seems fixed the problem peter mentioned above in the [latest version of beardown](https://github.com/wuusn/beardown/pull/4).

Run `gem update` and check the version of **beardown** is up date to **0.1.6.1**.
Then try **miyano** again.

**Comment by peterwooley** [comment]
After updating, the markdown links are now properly rendered individually. Thanks, @wuusn!

![screen shot 2019-01-15 at 1 58 16 pm](https://user-images.githubusercontent.com/42030/51212586-becd5200-18cd-11e9-80bb-98012da5ba37.png)

**Comment by wuusn** [comment]
@peterwooley It's my pleasure. It feels nice to help people like you, you made the issue very clearly, and also give me the feedback. You've made my day! Thanks!! ^ ^
