### ISSUE TITLE
Unordered lists using the * symbol are not rendered properly

### ISSUE THREAD

**Issue by peterwooley** [wuusn/miyano#18]
When using `*` as the unordered list symbol, lists are not rendered properly.

When using `*` or `-` as unordered list symbols in Bear, they're both rendered with a red bullet:

![unordered-lists-in-bear](https://user-images.githubusercontent.com/42030/50679555-caa94200-0fb8-11e9-9c0a-609e2f3bf986.png)

When rendered in Miyano, only the list items using the `-` symbol are rendered with as expected:

![unordered-lists-in-miyano](https://user-images.githubusercontent.com/42030/50679596-f298a580-0fb8-11e9-917a-ab838e2952a2.png)

Here's the example text I'm using:

```
* List item starting with *
* Another list item starting with *

- List item starting with -
- Another list item starting with -
```

**Comment by wuusn** [comment]
hi @peterwooley 
sorry for the delay.

Are you using the **Markdown Compatibility Mode**?
Which version of the Bear App you are using?

**Comment by peterwooley** [comment]
Hi @wuusn!

I'm using Markdown Compatibility Mode (both in Bear and in my Miyano blog with the `-m` flag) and running Bear Version 1.6.7 (6981). I'm also running macOS 10.13.6, if that could affect it.

**Comment by wuusn** [comment]
hi @peterwooley ,
I seems fixed the problem in [the latest beardown-compat](https://github.com/wuusn/beardown-compat/pull/1).
Run `gem update`, and make sure the version of  **beardown-compat** is up to **0.1.4**.
Then `miyano build; miyano try` your posts again.

I am not using the compatibility mode, any question from you is welcome!

**Comment by peterwooley** [comment]
Terrific! I updated and my lists are now rendering properly.

![screen shot 2019-01-15 at 1 57 04 pm](https://user-images.githubusercontent.com/42030/51212485-79108980-18cd-11e9-86fc-ea385b1a87a0.png)


Thanks for fixing this!
