### ISSUE TITLE
How to use Font Awesome with miyano ?

### ISSUE THREAD

**Issue by fmelodia** [wuusn/miyano#8]
I try to adapt your default settings to my use, and I try to use Font Awesome.

I followed [this procedure](https://fontawesome.com/how-to-use/web-fonts-with-css#less-and-sass), add `@import "scss/fontawesome.scss";` and `@import "scss/fa-solid.scss";` in default.scss, and copy **webfonts** in the folder **layout**.

After 'miyano build', the css seems correctly upgraded, but the folder **layout** is not present in **_site**

**Comment by wuusn** [comment]
hi @fmelodia ,

Sorry for the delay.

The easiest way to use **Font Awesome** seems to use it online.([found here](https://fontawesome.com/get-started))

Just insert the stylesheet in the `html` files.

I give you an example I have tested.( See `layout/*.html.erb` and the way they look like after `build` and `try`)

[font_awe_example.zip](https://github.com/wuusn/miyano/files/2057213/font_awe_example.zip)

Thanks for your issues.
